"""Add title to tasks and name to tags

Revision ID: 254978c7573e
Revises: 8d41f9fb0672
Create Date: 2025-01-20 03:08:21.057401+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '254978c7573e'
down_revision: Union[str, None] = '8d41f9fb0672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add 'name' column to 'tags' table as nullable
    op.add_column('tags', sa.Column('name', sa.String(), nullable=True))
    
    # Populate 'name' column with default values for existing records
    op.execute("UPDATE tags SET name = 'Unnamed Tag' WHERE name IS NULL")
    
    # Alter 'name' column to be non-nullable
    op.alter_column('tags', 'name',
               existing_type=sa.String(),
               nullable=False)
    
    # Add 'title' column to 'tasks' table as nullable
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=True))
    
    # Populate 'title' column with default values for existing records
    op.execute("UPDATE tasks SET title = 'Untitled Task' WHERE title IS NULL")
    
    # Alter 'title' column to be non-nullable
    op.alter_column('tasks', 'title',
               existing_type=sa.String(),
               nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove 'title' column from 'tasks' table
    op.drop_column('tasks', 'title')
    
    # Remove 'name' column from 'tags' table
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
