"""cascaded processing job when video is deleted

Revision ID: 213e65b53f51
Revises: 3c4b3b02087a
Create Date: 2025-01-03 20:30:08.652206+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213e65b53f51'
down_revision: Union[str, None] = '3c4b3b02087a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('processing_jobs_video_id_fkey', 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.create_foreign_key('processing_jobs_video_id_fkey', 'processing_jobs', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###
