"""Remove encoding field from Speaker model

Revision ID: 2a95946bde2a
Revises: 5326b206dd2a
Create Date: 2024-12-06 15:02:35.351759+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a95946bde2a'
down_revision: Union[str, None] = '5326b206dd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'encoding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('encoding', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
