"""Add thumbnail_url to videos table

Revision ID: 3c4b3b02087a
Revises: d7d0bbdab5c6
Create Date: 2025-01-02 23:01:00.674570+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4b3b02087a'
down_revision: Union[str, None] = 'd7d0bbdab5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_url')
    # ### end Alembic commands ###
