"""Add embedding to Speaker model

Revision ID: 4ccf6ec67f00
Revises: cd3b37c15863
Create Date: 2024-12-06 16:13:00.445361+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ccf6ec67f00'
down_revision: Union[str, None] = 'cd3b37c15863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('embedding', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'embedding')
    # ### end Alembic commands ###
