"""changed upload path nullable to true for deletion purposes

Revision ID: 59a1e6e11da0
Revises: 213e65b53f51
Create Date: 2025-01-04 02:57:37.326551+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a1e6e11da0'
down_revision: Union[str, None] = '213e65b53f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'upload_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'upload_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
