"""Standardize get_db function and update route imports

Revision ID: 5e708d45e6a4
Revises: 6952a82e2ab6
Create Date: 2024-10-09 00:08:02.927894+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e708d45e6a4'
down_revision: Union[str, None] = '6952a82e2ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
