"""Add thumbnail_path to Speaker

Revision ID: 9f1d8e2298b5
Revises: ab45760e03ba
Create Date: 2024-10-10 21:49:58.103519+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1d8e2298b5'
down_revision: Union[str, None] = 'ab45760e03ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'thumbnail_path')
    # ### end Alembic commands ###
