"""Add encoding column to speakers

Revision ID: ab45760e03ba
Revises: 5e708d45e6a4
Create Date: 2024-10-09 01:55:47.167288+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab45760e03ba'
down_revision: Union[str, None] = '5e708d45e6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('encoding', sa.LargeBinary(), nullable=False))
    op.drop_column('speakers', 'face_encoding')
    op.drop_column('speakers', 'thumbnail_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('thumbnail_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('speakers', sa.Column('face_encoding', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('speakers', 'encoding')
    # ### end Alembic commands ###
