"""Add unique_speaker_id to Speaker model

Revision ID: c88bbf6a3f34
Revises: 4ccf6ec67f00
Create Date: 2024-12-06 16:23:18.457984+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88bbf6a3f34'
down_revision: Union[str, None] = '4ccf6ec67f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('unique_speaker_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'unique_speaker_id')
    # ### end Alembic commands ###
